import clsx from "clsx";
type Group7HelperProps = {
  additionalClassNames?: string;
};

function Group7Helper({ additionalClassNames = "" }: Group7HelperProps) {
  return (
    <div className={clsx("absolute flex items-center justify-center size-[3px]", additionalClassNames)}>
      <div className="flex-none rotate-180">
        <div className="bg-black size-[3px]" />
      </div>
    </div>
  );
}

export default function Group() {
  return (
    <div className="relative size-full">
      <div className="absolute bg-black left-[114.98px] size-[3px] top-0" />
      <div className="absolute bg-black left-[114.98px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[117.98px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[114.98px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[111.98px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[111.98px] size-[3px] top-0" />
      <div className="absolute bg-black left-[111.98px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[111.98px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[111.98px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[111.98px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[111.98px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[117.98px] size-[3px] top-0" />
      <div className="absolute bg-black left-[120.98px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[114.98px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[120.98px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[114.98px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[120.98px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[123.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[120.98px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[114.98px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[120.98px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[114.98px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[120.98px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[123.98px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[123.98px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[123.98px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[123.98px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[120.98px] size-[3px] top-0" />
      <div className="absolute bg-black left-[3px] size-[3px] top-0" />
      <div className="absolute bg-black left-[147.98px] size-[3px] top-0" />
      <div className="absolute bg-black left-[21px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[38.99px] size-[3px] top-[6px]" />
      <Group7Helper additionalClassNames="left-[27px] top-[12px]" />
      <Group7Helper additionalClassNames="left-[44.99px] top-[12px]" />
      <div className="absolute bg-black left-[3px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[147.98px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[3px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[147.98px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[21px] size-[3px] top-0" />
      <div className="absolute bg-black left-[38.99px] size-[3px] top-0" />
      <Group7Helper additionalClassNames="left-[27px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[44.99px] top-[18px]" />
      <div className="absolute bg-black left-[3px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[147.98px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[21px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[38.99px] size-[3px] top-[3px]" />
      <Group7Helper additionalClassNames="left-[27px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[44.99px] top-[15px]" />
      <div className="absolute bg-black left-[3px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[147.98px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[3px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[147.98px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[3px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[147.98px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-0 size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[144.98px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[18px] size-[3px] top-0" />
      <div className="absolute bg-black left-[36px] size-[3px] top-0" />
      <Group7Helper additionalClassNames="left-[30px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[47.99px] top-[18px]" />
      <div className="absolute bg-black left-0 size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[144.98px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[18px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[36px] size-[3px] top-[3px]" />
      <Group7Helper additionalClassNames="left-[30px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[47.99px] top-[15px]" />
      <div className="absolute bg-black left-0 size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[144.98px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-0 size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[144.98px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-0 size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[144.98px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[6px] size-[3px] top-0" />
      <div className="absolute bg-black left-[150.98px] size-[3px] top-0" />
      <div className="absolute bg-black left-[24px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[41.99px] size-[3px] top-[6px]" />
      <Group7Helper additionalClassNames="left-[24px] top-[12px]" />
      <Group7Helper additionalClassNames="left-[41.99px] top-[12px]" />
      <div className="absolute bg-black left-[24px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[41.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[6px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[150.98px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[9px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[153.98px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[27px] size-[3px] top-0" />
      <div className="absolute bg-black left-[44.99px] size-[3px] top-0" />
      <Group7Helper additionalClassNames="left-[21px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[38.99px] top-[18px]" />
      <div className="absolute bg-black left-[9px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[153.98px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[27px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[44.99px] size-[3px] top-[3px]" />
      <Group7Helper additionalClassNames="left-[21px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[38.99px] top-[15px]" />
      <div className="absolute bg-black left-[9px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[153.98px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[9px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[153.98px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[9px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[153.98px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[12px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[156.98px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[30px] size-[3px] top-0" />
      <div className="absolute bg-black left-[47.99px] size-[3px] top-0" />
      <Group7Helper additionalClassNames="left-[18px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[35.99px] top-[18px]" />
      <div className="absolute bg-black left-[12px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[156.98px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[30px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[47.99px] size-[3px] top-[3px]" />
      <Group7Helper additionalClassNames="left-[18px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[35.99px] top-[15px]" />
      <div className="absolute bg-black left-[12px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[156.98px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[12px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[156.98px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[12px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[156.98px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[9px] size-[3px] top-0" />
      <div className="absolute bg-black left-[153.98px] size-[3px] top-0" />
      <div className="absolute bg-black left-[27px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[44.99px] size-[3px] top-[6px]" />
      <Group7Helper additionalClassNames="left-[21px] top-[12px]" />
      <Group7Helper additionalClassNames="left-[38.99px] top-[12px]" />
      <div className="absolute bg-black left-[9px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[153.98px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[63.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[63.99px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[60.99px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[63.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[81.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[132.98px] size-[3px] top-0" />
      <div className="absolute bg-black left-[96.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[105.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[96.99px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[105.99px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[63.99px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[60.99px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[96.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[105.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[96.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[105.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[96.99px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[105.99px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[66.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[63.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[60.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[63.99px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[60.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[78.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[129.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[129.99px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[93.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[102.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[93.99px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[102.99px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[93.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[102.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[93.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[102.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[93.99px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[102.99px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[60.99px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[66.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[84.99px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[135.99px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[81.99px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[132.98px] size-[3px] top-[6px]" />
      <div className="absolute bg-black left-[84.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[135.98px] size-[3px] top-0" />
      <Group7Helper additionalClassNames="left-[84.99px] top-[12px]" />
      <Group7Helper additionalClassNames="left-[135.99px] top-[12px]" />
      <Group7Helper additionalClassNames="left-[81.99px] top-[12px]" />
      <Group7Helper additionalClassNames="left-[132.98px] top-[12px]" />
      <Group7Helper additionalClassNames="left-[84.99px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[135.99px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[81.99px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[132.98px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[84.99px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[135.99px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[81.99px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[132.98px] top-[18px]" />
      <div className="absolute bg-black left-[84.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[135.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[81.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[132.98px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[84.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[135.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[81.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[132.98px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[66.99px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[69.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[87.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[138.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[138.99px] size-[3px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[96.99px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[102.99px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[99.99px] top-[18px]" />
      <Group7Helper additionalClassNames="left-[96.99px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[105.99px] top-[15px]" />
      <div className="absolute bg-black left-[69.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[72.99px] size-[3px] top-[9px]" />
      <div className="absolute bg-black left-[69.99px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[69.99px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[72.99px] size-[3px] top-[3px]" />
      <div className="absolute bg-black left-[72.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[60.99px] size-[3px] top-0" />
      <Group7Helper additionalClassNames="left-[93.99px] top-[15px]" />
      <Group7Helper additionalClassNames="left-[102.99px] top-[15px]" />
      <div className="absolute bg-black left-[72.99px] size-[3px] top-[12px]" />
      <div className="absolute bg-black left-[72.99px] size-[3px] top-[15px]" />
      <div className="absolute bg-black left-[72.99px] size-[3px] top-[18px]" />
      <div className="absolute bg-black left-[69.99px] size-[3px] top-0" />
      <div className="absolute bg-black left-[69.99px] size-[3px] top-[18px]" />
    </div>
  );
}
